services:
  tempo:
    image: grafana/tempo:2.5.0
    command:
      - -config.file=/etc/tempo.yaml
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
  prometheus:
    image: prom/prometheus:v2.52.0
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
  grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - ./config/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - 3000:3000
  otel-collector:
    image: otel/opentelemetry-collector:0.101.0
    restart: always
    command:
      - --config=/etc/otel-config.yaml
    volumes:
      - ./config/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - 4317:4317
