scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
